/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.112
 * Generated at: 2025-12-03 05:16:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1763622850000L));
    _jspx_dependants.put("jar:file:/D:/A.%20Xiamen/2025%20-%2009/Software%20Verification%20and%20Validation/Assignment%202%20-%20Group/DefectLoginSystem/Tomcat/webapps/Login_V/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<title>Document</title>\r\n");
      out.write("<style>\r\n");
      out.write("input:invalid:not(:placeholder-shown) {\r\n");
      out.write("	border-color: #dc3545;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input:valid:not(:placeholder-shown) {\r\n");
      out.write("	border-color: #198754;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input:invalid:not(:placeholder-shown) ~ .invalid-feedback {\r\n");
      out.write("	display: block;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"bg-light\">\r\n");
      out.write("\r\n");
      out.write("	<main class=\"flex-grow-1 d-flex align-items-center py-5\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row justify-content-center\">\r\n");
      out.write("				<div class=\"col-md-6 col-lg-4\">\r\n");
      out.write("\r\n");
      out.write("					<div class=\"card shadow-sm border-0\">\r\n");
      out.write("						<div class=\"card-body p-4\">\r\n");
      out.write("\r\n");
      out.write("							<div class=\"text-center mb-4\">\r\n");
      out.write("								<i class=\"fas fa-user-circle text-primary mb-3\"\r\n");
      out.write("									style=\"font-size: 3rem;\"></i>\r\n");
      out.write("								<h2 class=\"h4 text-dark fw-bold\">Welcome Back</h2>\r\n");
      out.write("								<p class=\"text-muted small\">Sign in to your account</p>\r\n");
      out.write("							</div>\r\n");
      out.write("							\r\n");
      out.write("							");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("						<form method=\"post\" action=\"Login\">\r\n");
      out.write("								<div class=\"mb-3\">\r\n");
      out.write("									<label for=\"username\" class=\"form-label fw-semibold\"> <i\r\n");
      out.write("										class=\"fas fa-user text-muted me-1\"></i> Username\r\n");
      out.write("									</label> <input type=\"text\" class=\"form-control form-control-lg\"\r\n");
      out.write("										id=\"username\" name=\"username\"\r\n");
      out.write("										placeholder=\"Enter your username\" required\r\n");
      out.write("										autocomplete=\"username\" minlength=\"2\" maxlength=\"25\"\r\n");
      out.write("										pattern=\"^[a-zA-Z0-9_]{2,25}$\"\r\n");
      out.write("										onkeypress=\"return event.charCode !=32\"\r\n");
      out.write("										title=\"Username must be 2-25 characters and contain only letters, numbers, and underscores\">\r\n");
      out.write("									<div class=\"invalid-feedback\">Please enter a valid\r\n");
      out.write("										username (2-25 characters, letters, numbers, and underscores\r\n");
      out.write("										only).</div>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("								<div class=\"mb-4\">\r\n");
      out.write("									<label for=\"password\" class=\"form-label fw-semibold\"> <i\r\n");
      out.write("										class=\"fas fa-lock text-muted me-1\"></i> Password\r\n");
      out.write("									</label> <input type=\"password\" class=\"form-control form-control-lg\"\r\n");
      out.write("										id=\"password\" name=\"password\"\r\n");
      out.write("										placeholder=\"Enter your password\" required	\r\n");
      out.write("										onkeypress=\"return event.charCode !=32\"\r\n");
      out.write("										autocomplete=\"current-password\" minlength=\"8\" maxlength=\"12\">\r\n");
      out.write("									<div class=\"invalid-feedback\">Please enter your password\r\n");
      out.write("										(at least 8 characters).</div>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("								<div class=\"mb-3\">\r\n");
      out.write("									<div class=\"form-check\">\r\n");
      out.write("										<input class=\"form-check-input\" type=\"checkbox\"\r\n");
      out.write("											id=\"rememberMe\" name=\"rememberMe\"> <label\r\n");
      out.write("											class=\"form-check-label text-muted\" for=\"rememberMe\">\r\n");
      out.write("											Remember me on this device </label>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("								<div class=\"d-grid mb-3\">\r\n");
      out.write("									<button type=\"submit\"\r\n");
      out.write("										class=\"btn btn-primary btn-lg fw-semibold\">\r\n");
      out.write("										<i class=\"fas fa-sign-in-alt me-2\"></i> Login\r\n");
      out.write("									</button>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("								<div class=\"text-center mb-3\">\r\n");
      out.write("									<a href=\"ForgetPassword.jsp\"\r\n");
      out.write("										class=\"text-decoration-none small text-muted\"> Forgot your\r\n");
      out.write("										password? </a>\r\n");
      out.write("								</div>\r\n");
      out.write("							</form>\r\n");
      out.write("\r\n");
      out.write("							<hr class=\"my-4\">\r\n");
      out.write("							<div class=\"text-center\">\r\n");
      out.write("								<p class=\"text-muted small mb-2\">Don't have an account?</p>\r\n");
      out.write("\r\n");
      out.write("								<a href=\"Register\"\r\n");
      out.write("									class=\"btn btn-outline-primary btn-sm fw-semibold\"> <i\r\n");
      out.write("									class=\"fas fa-user-plus me-1\"></i> Register here\r\n");
      out.write("								</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"text-center mt-4\">\r\n");
      out.write("						<p class=\"small text-muted\">\r\n");
      out.write("							<i class=\"fas fa-shield-alt text-success me-1\"></i> Your\r\n");
      out.write("							information is secure and protected\r\n");
      out.write("						</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</main>\r\n");
      out.write("\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /Login.jsp(48,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty loginError}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("								<div class=\"alert alert-danger text-center\">");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginError}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("</div>\r\n");
        out.write("							");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }
}
